server:
  port: 8081

spring:
  application:
    name: customer-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    template:
      message-converter: jackson2JsonMessageConverter

  datasource:
    url: jdbc:mysql://localhost:3306/foodie_db
    username: root
    password: Imak@143
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      hibernate:
        SQL: error
        type:
          descriptor:
            sql:
              BasicBinder: error
