server:
  port: 8082

spring:
  application:
    name: restaurant-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    listener:
      simple:
        message-converter: jackson2JsonMessageConverter

  datasource:
    url: jdbc:mysql://localhost:3306/foodie_db
    username: root
    password: Imak@143
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect